version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

executors:
  my-executor:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/repo
  
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
